### ISSUE TITLE
Issue in the Migration

### ISSUE THREAD

**Issue by malobaidan** [rafaelurben/django-discordbot#54]
There is an issue in the migration on the file 0003_amongusgame when adding this app to my django app, I got this error:

**django.db.utils.ProgrammingError: cannot cast type timestamp with time zone to boolean
LINE 1: ...r_connected" TYPE boolean USING "tracker_connected"::boolean**

 I guess someone changed tracker_connected field to boolean from timestamp from the database? this is why django is panicking, to solve this I deleted the column from the DB and created new Boolean  one with the same name.

**Comment by rafaelurben** [comment]
Oh, that could be. I actually didn't think that someone else used this app and may have broken a migration. I also haven't updated this in a while because an among us update broke the tracker because they changed some visuals. But I'll look into it, thanks!

**Comment by rafaelurben** [comment]
Oh yeah, I see what you mean. I created tracker_connected in migration 003 as DateTimeField and changed it in 004 to a BooleanField. MySql seemed to have no problem with that, but I'll fix this in a pull.
